### PR TITLE
Fatal error: concurrent map writes

### PR DESCRIPTION
**Pull request by scttnlsn**
Hi, 
I was having a look at queued and decided to run some quick performance test. It have crashed very quickly . 
I am attaching the panic error log.  
[stderr.txt](https://github.com/scttnlsn/queued/files/627351/stderr.txt)

The command i ran was : 
`queued -store memory`
I used wrk to benchmark it: 
`wrk -c 512 -t 1 -d 10 -s wrk.queue.post.lua  http://127.0.0.1:5353/testqueue`
where the `wrk.queue.post.lua` did set the method and body : 
```
wrk.method = "POST"
wrk.body = "TEST_ELEMENT"
```

### CODE REVIEW

**Comment by scttnlsn** [comment]
Attached a commit here to fix the issue.  Would you mind testing this out?  Thanks!

**Comment by szank** [comment]
Yep, it is working now. 
Also, I was wondering if it is intended or not, but when send a POST req to the /:queue/dequeue endpoint than when i call 
`curl -X GET http://localhost:5353/testqueue`
I get this : 
`{"depth":0,"dequeued":4155205,"enqueued":1686632,"timeouts":0}`. The depth is incremented on every deqeueue request, even if there is no data in the queueue.

**Comment by scttnlsn** [comment]
The depth is incremented?  I see the `dequeued` count increasing even when there's no data to dequeue.  This should probably only increment when there's actual data to dequeue.  I'll submit a separate PR.  Thanks!

**Comment by szank** [comment]
Sorry, my bad. The `dequeued` count have been incremented on each request, regardless if something was actually dequeued or not.

**Pull request merged**
