### PR TITLE
ErrNotFound is now in the errors package of goleveldb.

### PR DESCRIPTION
**Pull request by Lanzafame**

### CODE REVIEW

**Comment by scttnlsn** [comment]
Thanks!

**Comment by scttnlsn** [comment]
@Lanzafame Curious to hear your take on `goleveldb` as well: https://github.com/scttnlsn/queued/pull/8#issuecomment-174194187

**Comment by Lanzafame** [comment]
@scttnlsn Haha to be honest, I didn't want to install the `leveldb` dependency :sweat_smile:. I haven't used `goleveldb`, I was actually looking at implementing a BoltDB backend for queued, purely for familiarity sake on my part. So sorry can't really comment on `goleveldb`.

**Comment by scttnlsn** [comment]
No worries.  BoltDB looks interesting.  Feel free to submit a PR with a `boltdb` store! :smiley:

**Pull request merged**
